/*
 * SPDX-License-Identifier: GPL-2.0
 * Copyright (c) 2026 MCST
 */

/****************** PROTECTED SYSCALL DIAGNOSTIC MESSAGE IDS *******************/

#ifndef _E2K_PROTECTED_DIAG_MSG_IDS_H_
#define _E2K_PROTECTED_DIAG_MSG_IDS_H_

#ifdef CONFIG_PROTECTED_MODE


/*
 * Protected mode diagnostic message ID's:
 * NB> Add new messages at the bottom of the array only !!!
 *	ID's are fixed as these are used in qualification tests.
 */
enum pm_syscall_err_msg_id {
	PMSCERRMSG_ERR_ID,
	/* Syscall arg related messages: */
	PMSCERRMSG_UNEXP_ARG_TAG_ID,
	PMSCERRMSG_SC_ARG_SIZE_TOO_LITTLE,
	PMSCERRMSG_SC_ARGNAME_VAL_EXCEEDS_DSCR_MAX,
	PMSCERRMSG_SC_ARGNUM_VAL_EXCEEDS_DSCR_MAX,
	PMSCERRMSG_NOT_DESCR_IN_SC_ARG,
	PMSCERRMSG_NOT_DESCR_IN_SC_ARG_NAME,
	PMSCERRMSG_UNEXPECTED_DESCR_IN_SC_ARG,
	PMSCERRMSG_NOT_STRING_IN_SC_ARG,
	PMSCERRMSG_COUNT_EXCEEDS_DESCR_SIZE,
	PMSCERRMSG_NEGATIVE_SIZE_VALUE,
	PMSCERRMSG_BAD_STRUCT_IN_SC_ARG,
	PMSCERRMSG_BAD_UNSUPP_VAL_IN_SC_ARG,
	PMSCERRMSG_PTR_SIZE_TOO_LITTLE,
	PMSCERRMSG_SC_BAD_STRUCT_INT_FIELD,
	PMSCERRMSG_SC_UNEXPECTED_FUNC_IN_ARG,
	PMSCERRMSG_SC_NOT_DESCR_IN_FIELD,
	PMSCERRMSG_SC_NOT_DESCR_IN_STRUCT_FIELD,

	PMSCERRMSG_SC_BAD_STRUCT_IN_ARG_NAME,
	PMSCERRMSG_SC_BAD_FIELD_STRUCT_IN_ARG_NAME,
	PMSCERRMSG_SC_FAILED_TO_LOAD_LIBRARY,
	PMSCERRMSG_SC_BAD_ARG_VALUE,
	PMSCERRMSG_SC_ARG_SIZE_DIFFERS_STRUCT_SIZE,
	PMSCERRMSG_SC_ARG_SIZE_MISMATCHES_FIELD_VAL,
	PMSCERRMSG_SC_FAILED_TO_UPDATE_STRUCT,
	PMSCERRMSG_SC_WRONG_ARG_VALUE_LX,
	PMSCERRMSG_SC_WRONG_ARG_VALUE_LX_TAG,
	PMSCERRMSG_SC_UNEXPECTED_ARG_VALUE,
	PMSCERRMSG_SC_CMD_WRONG_ARG_VALUE_LX,
	PMSCERRMSG_SC_ARG_VAL_EXCEEDS_DSCR_SIZE,
	PMSCERRMSG_SC_ARG_VAL_UNSUPPORTED,
	PMSCERRMSG_SC_ARGPTR_SIZE_TOO_LITTLE,
	PMSCERRMSG_NOT_DESCR_IN_SC_ARG_NAME_TAG,

	/* Structure analysis related messages: */
	PMSCERRMSG_STRUCT_UNALIGNED_DESCR,
	PMSCERRMSG_STRUCT_UNINIT_INT_FIELD,
	PMSCERRMSG_STRUCT_BAD_TAG_INT_FIELD,
	PMSCERRMSG_STRUCT_NOT_PL_IN_FIELD,
	PMSCERRMSG_STRUCT_NOT_DSCR_IN_FIELD,
	PMSCERRMSG_STRUCT_FAILED_TO_READ_FIELD,
	PMSCERRMSG_INSUFFICIENT_STRUCT_SIZE,

	/* convert_array related messages: */
	PMCNVSTRMSG_STRUCT_SIZE_EXCEEDS_MAX,
	PMCNVSTRMSG_STRUCT_DESCR_UNALIGNED,
	PMCNVSTRMSG_STRUCT_DOESNT_CONTAIN_DESCR,

	/* sigaltstack() related message: */
	PMSIGALTSTMSG_ERR_BOTH_SS_EMPTY,
	/* clean_descriptors related message: */
	PMCLNDSCRSMSG_WRONG_ARG_SIZE,
	PMCLNDSCRSMSG_EXITED_WITH_ERR,
	/* mmap() related messages: */
	PMMMAPMSG_ATTEMPT_TO_MAP_BYTES,
	PMMMAPMSG_CANT_MAP_OVER_2GB,
	PMMMAPMSG_CANT_REMAP_OVER_ALLOCATED,
	PMSCERRMSG_UNSUPPORTED_FLAG,
	/* mprotect() related message: */
	PMSCWARN_DSCR_PROT_MISMATCH,
	/* Other messages: */
	PMSCERRMSG_EMPTY_STRUCTURE_FIELD,
	PMSCERRMSG_COUNT_EXCEEDS_LIMIT,
	PMSCERRMSG_UNEXPECTED_FIELD_TAG,
	/* Warnings: */
	PMMMAPMSG_DSCR_WITHOUT_ACCESS_RIGHTS,
	PMSCWARN_SOCKETCALL_FAILED_TO_UPDATE_FLD,
	PMSCWARN_PROC_RETURNED_ERROR,
	PMSCWARN_TAGS_GET_LOST_WHEN_READ,
	PMSCWARN_NEGATIVE_DSCR_SIZE,
	PMSCWARN_ADDR_IN_SIGINFO,

	PMSCERRMSG_SC_NOT_AVAILABLE_IN_PM,
	PMSCERRMSG_FUNC_NOT_AVAILABLE_IN_PM,
	PMSCERRMSG_FATAL_READ_FROM,
	PMSCERRMSG_FATAL_READ_ERR_FROM,
	PMSCERRMSG_FATAL_WRITE_AT,
	PMSCERRMSG_FATAL_WRITE_AT_FIELD,
	PMSCERRMSG_FATAL_DESCR_IN_STACK,

	PMSCERRMSG_EXECUTION_TERMINATED,

	/* Comment messages: */
	PMSCERRMSG_SC_ARG_COUNT_TRUNCATED,
	PMSCERRMSG_SC_ARG_MISSED_OR_UNINIT,
	PMSCERRMSG_STRUCT_FIELD_VAL_IGNORED,
	PMSCWARN_DSCR_COMPONENTS,

	/* read/write related message: */
	PMSCERRMSG_DSCR_WITHOUT_READ_PERM,
	PMSCERRMSG_DSCR_WITHOUT_WRITE_PERM,
	PMSCERRMSG_UNEXPECTED_TAG_IN_BUFF,
	PMSCERRMSG_CUI_NOT_FOUND,
	PMSCERRMSG_CUI_MISMATCH_IN_PL_IP,

	PMSCERRMSG_SC_NOT_DSCR_TAG_STRCT_FLD_VAL,
	PMSCERRMSG_SC_NOT_YET_SUPPORTED_IN_PM,
	PMSCERRMSG_SC_BRK_NON_ZERO_ARG_IN_PM,

	PMSCWARN_MMAP_SHARED_FLAG,

	/* MISC: */
	PMSCWARN_UNALIGNED_PL_IN_ARG,
	PMSCERRMSG_SC_NOT_ENABLED,
	PMSCWARN_UNALIGNED_DSCR_IN_ARG,
	PMSCERRMSG_SC_ALLOWED_IN_SOFT_MODE,
	PMSCERRMSG_SC_CLEAN_DESCR_IN_UNSAFE,
	PMSCERRMSG_SC_WRONG_ARG_VALUE_LX_vs_LX,

	/* NB> New messages to add above this line */
	/* Unclassified */ PMSCERRMSG_FILLING_FREED_MEM_BLOCKED,
	/* Unclassified */ PMSCERRMSG_FILLING_FREED_MEM_IN_UNSAFE_PM,
	/* Unclassified */ PMSCERRMSG_THIS_IS_UNSAFE_BINARY,
	/* Unclassified */ PMSCERRMSG_UNSAFE_SAP,
	/* Unclassified */ PMSCERRMSG_USE_TECH48,

	/* Intro diagnostic messages: */
	PMSCERRMSG_RUNTIME_ERROR,
	PMSCERRMSG_RUNTIME_WARNING,
	PMSCERRMSG_RUNTIME_PWARNING,

	/* Total message number: */
	PMSCERRMSG_NUMBER,

};

#define PMSC_NO_ID_ERRMSG_START1 PMSCERRMSG_EXECUTION_TERMINATED
#define PMSC_NO_ID_ERRMSG_FINAL1 PMSCERRMSG_CUI_MISMATCH_IN_PL_IP
#define PMSC_NO_ID_ERRMSG_START2 PMSCERRMSG_RUNTIME_ERROR
#define PMSC_NO_ID_ERRMSG_FINAL2 PMSCERRMSG_NUMBER

#endif /* CONFIG_PROTECTED_MODE */


#endif /* _E2K_PROTECTED_DIAG_MSG_IDS_H_ */

