 # SPDX-License-Identifier: GPL-2.0
 # Copyright (c) 2023 MCST
 
#
#  Makefile for the MCST device drivers.
#

elcan-objs := \
	elcan_pci.o \
	elcan_dev.o \
	elcan_debugfs.o

obj-$(CONFIG_CAN_ELCAN) += elcan.o
