#
# Makefile for the Linux kernel device drivers.
#

obj-$(CONFIG_R2000P_EDAC) += r2000p-edac/
obj-$(CONFIG_E90_FASTBOOT) += prom/
obj-$(CONFIG_E90S) += prom/
obj-$(CONFIG_E2K)  += prom/
obj-y += mvp/
obj-y += mpv/
obj-y += mgpm/
obj-y += mmrm/
obj-y += mmrse/
obj-y += rdma/
obj-y += rdma_sic/
obj-y += rdma_m/
obj-y += mokx/
obj-y += mpk/
obj-y += mokm/
obj-$(CONFIG_DMP_ASSIST) += dmp_assist/
obj-$(CONFIG_I2C_SPD) += i2c_spd/
obj-$(CONFIG_MCST_GPU_IMGTEC_R4991288) += gpu-imgtec.r4991288/
obj-$(CONFIG_MCST_GPU_IMGTEC_R5824814) += gpu-imgtec.r5824814/
obj-$(CONFIG_MCST_GPU_VIV) += gpu-viv/
obj-$(CONFIG_LPTOUTS) += lptouts/
obj-$(CONFIG_DRM_MGA2) += mga2/
obj-y += m2mlc/
obj-y += apkpwr/
obj-y += hantrodec/
obj-y += BigEv2/
obj-$(CONFIG_E2K) += pcs/
obj-$(CONFIG_E2K) += pcsm/
obj-$(CONFIG_PMC_R2KP) += pmc-r2kp/
obj-$(CONFIG_IMGTEC) += video-imgtec/
obj-$(CONFIG_DRM_SMI) += smi/
obj-$(CONFIG_SMI_PWM) += smi-pwm/
obj-$(CONFIG_SMI_GPIO) += smi-gpio/
obj-$(CONFIG_MEM2ALLOC) += mem2alloc/
obj-$(CONFIG_SENSORS_EMC2305)	+= emc/
obj-$(CONFIG_HW_CHECK) += hw_check/

