 # SPDX-License-Identifier: GPL-2.0
 # Copyright (c) 2023 MCST
 
#
# Makefile for the Linux kernel device drivers.
#

obj-$(CONFIG_R2000P_EDAC) += r2000p-edac/
obj-y += mpv/
obj-y += mmrse/
obj-$(CONFIG_MCST_GPU_IMGTEC_R4991288) += gpu-imgtec.r4991288/
obj-$(CONFIG_MCST_GPU_IMGTEC_R5878540) += gpu-imgtec.r5878540/
obj-$(CONFIG_MCST_GPU_VIV) += gpu-viv/
obj-$(CONFIG_DRM_MGA2) += mga2/
obj-$(CONFIG_DRM_MGA25) += mga25/
obj-y += hantrodec/
obj-y += BigEv2/
obj-$(CONFIG_E2K) += pcs/
obj-$(CONFIG_E2K) += pcsm/
obj-$(CONFIG_PMC_R2KP) += pmc-r2kp/
obj-$(CONFIG_IMGTEC) += video-imgtec/
obj-$(CONFIG_DRM_SMI) += smi/
obj-$(CONFIG_SMI_PWM) += smi-pwm/
obj-$(CONFIG_SMI_GPIO) += smi-gpio/
obj-$(CONFIG_MEM2ALLOC) += mem2alloc/
obj-$(CONFIG_SENSORS_EMC2305)	+= emc/
obj-$(CONFIG_HW_CHECK) += hw_check/
obj-$(CONFIG_FATAL_TEMP) += fatal_temp/
obj-$(CONFIG_L_I2S) += i2s/
obj-$(CONFIG_DS125DF111) += ds125df111/
