/*!
 *****************************************************************************
 *
 * @File       e5500_public_regdefs.h
 * @Title      VXE Encoder public register definitions
 * @Description    VXE Encoder public register definitions
 * ---------------------------------------------------------------------------
 *
 * Copyright (c) Imagination Technologies Ltd.
 * 
 * The contents of this file are subject to the MIT license as set out below.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"), 
 * to deal in the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in 
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
 * THE SOFTWARE.
 * 
 * Alternatively, the contents of this file may be used under the terms of the 
 * GNU General Public License Version 2 ("GPL")in which case the provisions of
 * GPL are applicable instead of those above. 
 * 
 * If you wish to allow use of your version of this file only under the terms 
 * of GPL, and not to allow others to use your version of this file under the 
 * terms of the MIT license, indicate your decision by deleting the provisions 
 * above and replace them with the notice and other provisions required by GPL 
 * as set out in the file called "GPLHEADER" included in this distribution. If 
 * you do not delete the provisions above, a recipient may use your version of 
 * this file under the terms of either the MIT license or GPL.
 * 
 * This License is also included in this distribution in the file called 
 * "MIT_COPYING".
 *
 *****************************************************************************/


/* Hardware versions */
#define MIN_30_REV 0x00030000
#define MAX_30_REV 0x00030099
#define MIN_32_REV 0x00030200
#define MAX_32_REV 0x00030299
#define MIN_34_REV 0x00030400
#define MAX_34_REV 0x00030499
#define MIN_36_REV 0x00030600
#define MAX_36_REV 0x00030699
#define MIN_39_REV 0x00030900
#define MAX_39_REV 0x00030999
#define MIN_40_REV 0x00040000
#define MAX_40_REV 0x00040099
#define MIN_50_REV 0x00050000
#define MAX_50_REV 0x00050299
#define MIN_53_REV 0x00050300
#define MAX_53_REV 0x00050399
#define MIN_60_REV 0x00060000
#define MAX_60_REV 0x00060099


/****************************** REGISTERS *******************************/


/* Register MULTIPIPE_SOFT_RESET */
#define QUARTZ_TOP_MULTIPIPE_SOFT_RESET 0x0000
#define MASK_QUARTZ_TOP_PROC_SOFT_RESET 0x00000001
#define SHIFT_QUARTZ_TOP_PROC_SOFT_RESET 0
#define REGNUM_QUARTZ_TOP_PROC_SOFT_RESET 0x0000
#define SIGNED_QUARTZ_TOP_PROC_SOFT_RESET 0
#define MAX_QUARTZ_TOP_PROC_SOFT_RESET 1
#define MIN_QUARTZ_TOP_PROC_SOFT_RESET 0

#define MASK_QUARTZ_TOP_CORE_SOFT_RESET 0x00000002
#define SHIFT_QUARTZ_TOP_CORE_SOFT_RESET 1
#define REGNUM_QUARTZ_TOP_CORE_SOFT_RESET 0x0000
#define SIGNED_QUARTZ_TOP_CORE_SOFT_RESET 0
#define MAX_QUARTZ_TOP_CORE_SOFT_RESET 1
#define MIN_QUARTZ_TOP_CORE_SOFT_RESET 0

#define MASK_QUARTZ_TOP_ENCODER_PIPE_SOFT_RESET(i) (0x00000001 << (4 + ((i) * 1)))
#define SHIFT_QUARTZ_TOP_ENCODER_PIPE_SOFT_RESET(i) (4 + ((i) * 1))
#define REGNUM_QUARTZ_TOP_ENCODER_PIPE_SOFT_RESET(i) 0x0000
#define MAX_QUARTZ_TOP_ENCODER_PIPE_SOFT_RESET 1
#define MIN_QUARTZ_TOP_ENCODER_PIPE_SOFT_RESET 0

/* Register MULTIPIPE_INT_STAT */
#define QUARTZ_TOP_MULTIPIPE_INT_STAT 0x0010
#define MASK_QUARTZ_TOP_INT_STAT_DMAC 0x00000001
#define SHIFT_QUARTZ_TOP_INT_STAT_DMAC 0
#define REGNUM_QUARTZ_TOP_INT_STAT_DMAC 0x0010
#define SIGNED_QUARTZ_TOP_INT_STAT_DMAC 0
#define MAX_QUARTZ_TOP_INT_STAT_DMAC 1
#define MIN_QUARTZ_TOP_INT_STAT_DMAC 0

#define MASK_QUARTZ_TOP_INT_STAT_PROC 0x00000002
#define SHIFT_QUARTZ_TOP_INT_STAT_PROC 1
#define REGNUM_QUARTZ_TOP_INT_STAT_PROC 0x0010
#define SIGNED_QUARTZ_TOP_INT_STAT_PROC 0
#define MAX_QUARTZ_TOP_INT_STAT_PROC 1
#define MIN_QUARTZ_TOP_INT_STAT_PROC 0

#define MASK_QUARTZ_TOP_INT_STAT_PROC_HALT 0x00000004
#define SHIFT_QUARTZ_TOP_INT_STAT_PROC_HALT 2
#define REGNUM_QUARTZ_TOP_INT_STAT_PROC_HALT 0x0010
#define SIGNED_QUARTZ_TOP_INT_STAT_PROC_HALT 0
#define MAX_QUARTZ_TOP_INT_STAT_PROC_HALT 1
#define MIN_QUARTZ_TOP_INT_STAT_PROC_HALT 0

#define MASK_QUARTZ_TOP_INT_STAT_MMU_FAULT 0x00000008
#define SHIFT_QUARTZ_TOP_INT_STAT_MMU_FAULT 3
#define REGNUM_QUARTZ_TOP_INT_STAT_MMU_FAULT 0x0010
#define SIGNED_QUARTZ_TOP_INT_STAT_MMU_FAULT 0
#define MAX_QUARTZ_TOP_INT_STAT_MMU_FAULT 1
#define MIN_QUARTZ_TOP_INT_STAT_MMU_FAULT 0

#define MASK_QUARTZ_TOP_INT_STAT_FRAME_ALARM 0x00000010
#define SHIFT_QUARTZ_TOP_INT_STAT_FRAME_ALARM 4
#define REGNUM_QUARTZ_TOP_INT_STAT_FRAME_ALARM 0x0010
#define SIGNED_QUARTZ_TOP_INT_STAT_FRAME_ALARM 0
#define MAX_QUARTZ_TOP_INT_STAT_FRAME_ALARM 1
#define MIN_QUARTZ_TOP_INT_STAT_FRAME_ALARM 0

#define MASK_QUARTZ_TOP_INT_STAT_PIPE_PROC 0x00000F00
#define SHIFT_QUARTZ_TOP_INT_STAT_PIPE_PROC 8
#define REGNUM_QUARTZ_TOP_INT_STAT_PIPE_PROC 0x0010
#define SIGNED_QUARTZ_TOP_INT_STAT_PIPE_PROC 0
#define MAX_QUARTZ_TOP_INT_STAT_PIPE_PROC 15
#define MIN_QUARTZ_TOP_INT_STAT_PIPE_PROC 0

#define MASK_QUARTZ_TOP_INT_STAT_PIPE_HOST 0x000F0000
#define SHIFT_QUARTZ_TOP_INT_STAT_PIPE_HOST 16
#define REGNUM_QUARTZ_TOP_INT_STAT_PIPE_HOST 0x0010
#define SIGNED_QUARTZ_TOP_INT_STAT_PIPE_HOST 0
#define MAX_QUARTZ_TOP_INT_STAT_PIPE_HOST 15
#define MIN_QUARTZ_TOP_INT_STAT_PIPE_HOST 0

#define MASK_QUARTZ_TOP_PROC_INT_STAT 0x40000000
#define SHIFT_QUARTZ_TOP_PROC_INT_STAT 30
#define REGNUM_QUARTZ_TOP_PROC_INT_STAT 0x0010
#define SIGNED_QUARTZ_TOP_PROC_INT_STAT 0
#define MAX_QUARTZ_TOP_PROC_INT_STAT 1
#define MIN_QUARTZ_TOP_PROC_INT_STAT 0

#define MASK_QUARTZ_TOP_HOST_INT_STAT 0x80000000
#define SHIFT_QUARTZ_TOP_HOST_INT_STAT 31
#define REGNUM_QUARTZ_TOP_HOST_INT_STAT 0x0010
#define SIGNED_QUARTZ_TOP_HOST_INT_STAT 0
#define MAX_QUARTZ_TOP_HOST_INT_STAT 1
#define MIN_QUARTZ_TOP_HOST_INT_STAT 0

/* Register MULTIPIPE_PROC_INT_ENAB */
#define QUARTZ_TOP_MULTIPIPE_PROC_INT_ENAB 0x0014
#define MASK_QUARTZ_TOP_PROC_INTEN_DMAC 0x00000001
#define SHIFT_QUARTZ_TOP_PROC_INTEN_DMAC 0
#define REGNUM_QUARTZ_TOP_PROC_INTEN_DMAC 0x0014
#define SIGNED_QUARTZ_TOP_PROC_INTEN_DMAC 0
#define MAX_QUARTZ_TOP_PROC_INTEN_DMAC 1
#define MIN_QUARTZ_TOP_PROC_INTEN_DMAC 0

#define MASK_QUARTZ_TOP_PROC_INTEN_PROC 0x00000002
#define SHIFT_QUARTZ_TOP_PROC_INTEN_PROC 1
#define REGNUM_QUARTZ_TOP_PROC_INTEN_PROC 0x0014
#define SIGNED_QUARTZ_TOP_PROC_INTEN_PROC 0
#define MAX_QUARTZ_TOP_PROC_INTEN_PROC 1
#define MIN_QUARTZ_TOP_PROC_INTEN_PROC 0

#define MASK_QUARTZ_TOP_PROC_INTEN_PROC_HALT 0x00000004
#define SHIFT_QUARTZ_TOP_PROC_INTEN_PROC_HALT 2
#define REGNUM_QUARTZ_TOP_PROC_INTEN_PROC_HALT 0x0014
#define SIGNED_QUARTZ_TOP_PROC_INTEN_PROC_HALT 0
#define MAX_QUARTZ_TOP_PROC_INTEN_PROC_HALT 1
#define MIN_QUARTZ_TOP_PROC_INTEN_PROC_HALT 0

#define MASK_QUARTZ_TOP_PROC_INTEN_MMU_FAULT 0x00000008
#define SHIFT_QUARTZ_TOP_PROC_INTEN_MMU_FAULT 3
#define REGNUM_QUARTZ_TOP_PROC_INTEN_MMU_FAULT 0x0014
#define SIGNED_QUARTZ_TOP_PROC_INTEN_MMU_FAULT 0
#define MAX_QUARTZ_TOP_PROC_INTEN_MMU_FAULT 1
#define MIN_QUARTZ_TOP_PROC_INTEN_MMU_FAULT 0

#define MASK_QUARTZ_TOP_PROC_INTEN_FRAME_ALARM 0x00000010
#define SHIFT_QUARTZ_TOP_PROC_INTEN_FRAME_ALARM 4
#define REGNUM_QUARTZ_TOP_PROC_INTEN_FRAME_ALARM 0x0014
#define SIGNED_QUARTZ_TOP_PROC_INTEN_FRAME_ALARM 0
#define MAX_QUARTZ_TOP_PROC_INTEN_FRAME_ALARM 1
#define MIN_QUARTZ_TOP_PROC_INTEN_FRAME_ALARM 0

#define MASK_QUARTZ_TOP_PROC_INTEN_PIPE_PROC 0x00000F00
#define SHIFT_QUARTZ_TOP_PROC_INTEN_PIPE_PROC 8
#define REGNUM_QUARTZ_TOP_PROC_INTEN_PIPE_PROC 0x0014
#define SIGNED_QUARTZ_TOP_PROC_INTEN_PIPE_PROC 0
#define MAX_QUARTZ_TOP_PROC_INTEN_PIPE_PROC 15
#define MIN_QUARTZ_TOP_PROC_INTEN_PIPE_PROC 0

#define MASK_QUARTZ_TOP_PROC_INTEN_PIPE_HOST 0x000F0000
#define SHIFT_QUARTZ_TOP_PROC_INTEN_PIPE_HOST 16
#define REGNUM_QUARTZ_TOP_PROC_INTEN_PIPE_HOST 0x0014
#define SIGNED_QUARTZ_TOP_PROC_INTEN_PIPE_HOST 0
#define MAX_QUARTZ_TOP_PROC_INTEN_PIPE_HOST 15
#define MIN_QUARTZ_TOP_PROC_INTEN_PIPE_HOST 0

/* Register MULTIPIPE_HOST_INT_ENAB */
#define QUARTZ_TOP_MULTIPIPE_HOST_INT_ENAB 0x0018
#define MASK_QUARTZ_TOP_HOST_INTEN_DMAC 0x00000001
#define SHIFT_QUARTZ_TOP_HOST_INTEN_DMAC 0
#define REGNUM_QUARTZ_TOP_HOST_INTEN_DMAC 0x0018
#define SIGNED_QUARTZ_TOP_HOST_INTEN_DMAC 0
#define MAX_QUARTZ_TOP_HOST_INTEN_DMAC 1
#define MIN_QUARTZ_TOP_HOST_INTEN_DMAC 0

#define MASK_QUARTZ_TOP_HOST_INTEN_PROC 0x00000002
#define SHIFT_QUARTZ_TOP_HOST_INTEN_PROC 1
#define REGNUM_QUARTZ_TOP_HOST_INTEN_PROC 0x0018
#define SIGNED_QUARTZ_TOP_HOST_INTEN_PROC 0
#define MAX_QUARTZ_TOP_HOST_INTEN_PROC 1
#define MIN_QUARTZ_TOP_HOST_INTEN_PROC 0

#define MASK_QUARTZ_TOP_HOST_INTEN_PROC_HALT 0x00000004
#define SHIFT_QUARTZ_TOP_HOST_INTEN_PROC_HALT 2
#define REGNUM_QUARTZ_TOP_HOST_INTEN_PROC_HALT 0x0018
#define SIGNED_QUARTZ_TOP_HOST_INTEN_PROC_HALT 0
#define MAX_QUARTZ_TOP_HOST_INTEN_PROC_HALT 1
#define MIN_QUARTZ_TOP_HOST_INTEN_PROC_HALT 0

#define MASK_QUARTZ_TOP_HOST_INTEN_MMU_FAULT 0x00000008
#define SHIFT_QUARTZ_TOP_HOST_INTEN_MMU_FAULT 3
#define REGNUM_QUARTZ_TOP_HOST_INTEN_MMU_FAULT 0x0018
#define SIGNED_QUARTZ_TOP_HOST_INTEN_MMU_FAULT 0
#define MAX_QUARTZ_TOP_HOST_INTEN_MMU_FAULT 1
#define MIN_QUARTZ_TOP_HOST_INTEN_MMU_FAULT 0

#define MASK_QUARTZ_TOP_HOST_INTEN_FRAME_ALARM 0x00000010
#define SHIFT_QUARTZ_TOP_HOST_INTEN_FRAME_ALARM 4
#define REGNUM_QUARTZ_TOP_HOST_INTEN_FRAME_ALARM 0x0018
#define SIGNED_QUARTZ_TOP_HOST_INTEN_FRAME_ALARM 0
#define MAX_QUARTZ_TOP_HOST_INTEN_FRAME_ALARM 1
#define MIN_QUARTZ_TOP_HOST_INTEN_FRAME_ALARM 0

#define MASK_QUARTZ_TOP_HOST_INTEN_PIPE_PROC 0x00000F00
#define SHIFT_QUARTZ_TOP_HOST_INTEN_PIPE_PROC 8
#define REGNUM_QUARTZ_TOP_HOST_INTEN_PIPE_PROC 0x0018
#define SIGNED_QUARTZ_TOP_HOST_INTEN_PIPE_PROC 0
#define MAX_QUARTZ_TOP_HOST_INTEN_PIPE_PROC 15
#define MIN_QUARTZ_TOP_HOST_INTEN_PIPE_PROC 0

#define MASK_QUARTZ_TOP_HOST_INTEN_PIPE_HOST 0x000F0000
#define SHIFT_QUARTZ_TOP_HOST_INTEN_PIPE_HOST 16
#define REGNUM_QUARTZ_TOP_HOST_INTEN_PIPE_HOST 0x0018
#define SIGNED_QUARTZ_TOP_HOST_INTEN_PIPE_HOST 0
#define MAX_QUARTZ_TOP_HOST_INTEN_PIPE_HOST 15
#define MIN_QUARTZ_TOP_HOST_INTEN_PIPE_HOST 0

/* Register MUILTIPIPE_INT_CLEAR */
#define QUARTZ_TOP_MULTIPIPE_INT_CLEAR 0x001C
#define MASK_QUARTZ_TOP_INTCLR_DMAC 0x00000001
#define SHIFT_QUARTZ_TOP_INTCLR_DMAC 0
#define REGNUM_QUARTZ_TOP_INTCLR_DMAC 0x001C
#define SIGNED_QUARTZ_TOP_INTCLR_DMAC 0
#define MAX_QUARTZ_TOP_INTCLR_DMAC  1
#define MIN_QUARTZ_TOP_INTCLR_DMAC  0

#define MASK_QUARTZ_TOP_INTCLR_PROC 0x00000002
#define SHIFT_QUARTZ_TOP_INTCLR_PROC 1
#define REGNUM_QUARTZ_TOP_INTCLR_PROC 0x001C
#define SIGNED_QUARTZ_TOP_INTCLR_PROC 0
#define MAX_QUARTZ_TOP_INTCLR_PROC  1
#define MIN_QUARTZ_TOP_INTCLR_PROC  0

#define MASK_QUARTZ_TOP_INTCLR_PROC_HALT 0x00000004
#define SHIFT_QUARTZ_TOP_INTCLR_PROC_HALT 2
#define REGNUM_QUARTZ_TOP_INTCLR_PROC_HALT 0x001C
#define SIGNED_QUARTZ_TOP_INTCLR_PROC_HALT 0
#define MAX_QUARTZ_TOP_INTCLR_PROC_HALT 1
#define MIN_QUARTZ_TOP_INTCLR_PROC_HALT 0

#define MASK_QUARTZ_TOP_INTCLR_MMU_FAULT 0x00000008
#define SHIFT_QUARTZ_TOP_INTCLR_MMU_FAULT 3
#define REGNUM_QUARTZ_TOP_INTCLR_MMU_FAULT 0x001C
#define SIGNED_QUARTZ_TOP_INTCLR_MMU_FAULT 0
#define MAX_QUARTZ_TOP_INTCLR_MMU_FAULT 1
#define MIN_QUARTZ_TOP_INTCLR_MMU_FAULT 0

#define MASK_QUARTZ_TOP_INTCLR_FRAME_ALARM 0x00000010
#define SHIFT_QUARTZ_TOP_INTCLR_FRAME_ALARM 4
#define REGNUM_QUARTZ_TOP_INTCLR_FRAME_ALARM 0x001C
#define SIGNED_QUARTZ_TOP_INTCLR_FRAME_ALARM 0
#define MAX_QUARTZ_TOP_INTCLR_FRAME_ALARM 1
#define MIN_QUARTZ_TOP_INTCLR_FRAME_ALARM 0

#define MASK_QUARTZ_TOP_INTCLR_PROC_FENCE_DONE 0x00000020
#define SHIFT_QUARTZ_TOP_INTCLR_PROC_FENCE_DONE 5
#define NBITS_QUARTZ_TOP_INTCLR_PROC_FENCE_DONE 1
#define REGNUM_QUARTZ_TOP_INTCLR_PROC_FENCE_DONE 0x001C
#define SIGNED_QUARTZ_TOP_INTCLR_PROC_FENCE_DONE 0
#define MAX_QUARTZ_TOP_INTCLR_PROC_FENCE_DONE 1
#define MIN_QUARTZ_TOP_INTCLR_PROC_FENCE_DONE 0

/* Register MULTIPIPE_AUTO_CLK_GATING */
#define QUARTZ_TOP_MULTIPIPE_AUTO_CLK_GATING 0x003C
#define MASK_QUARTZ_TOP_DMAC_AUTO_CLK_GATE_ENABLE 0x00000004
#define SHIFT_QUARTZ_TOP_DMAC_AUTO_CLK_GATE_ENABLE 2
#define REGNUM_QUARTZ_TOP_DMAC_AUTO_CLK_GATE_ENABLE 0x003C
#define SIGNED_QUARTZ_TOP_DMAC_AUTO_CLK_GATE_ENABLE 0
#define MAX_QUARTZ_TOP_DMAC_AUTO_CLK_GATE_ENABLE 1
#define MIN_QUARTZ_TOP_DMAC_AUTO_CLK_GATE_ENABLE 0

/* Register MULTIPIPE_MAN_CLK_GATING */
#define QUARTZ_TOP_MULTIPIPE_MAN_CLK_GATING 0x0040
#define MASK_QUARTZ_TOP_PROC_MAN_CLK_GATE_ENABLE 0x00000002
#define SHIFT_QUARTZ_TOP_PROC_MAN_CLK_GATE_ENABLE 1
#define REGNUM_QUARTZ_TOP_PROC_MAN_CLK_GATE_ENABLE 0x0040
#define SIGNED_QUARTZ_TOP_PROC_MAN_CLK_GATE_ENABLE 0
#define MAX_QUARTZ_TOP_PROC_MAN_CLK_GATE_ENABLE 1
#define MIN_QUARTZ_TOP_PROC_MAN_CLK_GATE_ENABLE 0

#define MASK_QUARTZ_TOP_DMAC_MAN_CLK_GATE_ENABLE 0x00000004
#define SHIFT_QUARTZ_TOP_DMAC_MAN_CLK_GATE_ENABLE 2
#define REGNUM_QUARTZ_TOP_DMAC_MAN_CLK_GATE_ENABLE 0x0040
#define SIGNED_QUARTZ_TOP_DMAC_MAN_CLK_GATE_ENABLE 0
#define MAX_QUARTZ_TOP_DMAC_MAN_CLK_GATE_ENABLE 1
#define MIN_QUARTZ_TOP_DMAC_MAN_CLK_GATE_ENABLE 0

#define MASK_QUARTZ_TOP_ENCODER_PIPE_MAN_CLK_GATE_ENABLE 0x000F0000
#define SHIFT_QUARTZ_TOP_ENCODER_PIPE_MAN_CLK_GATE_ENABLE 16
#define REGNUM_QUARTZ_TOP_ENCODER_PIPE_MAN_CLK_GATE_ENABLE 0x0040
#define SIGNED_QUARTZ_TOP_ENCODER_PIPE_MAN_CLK_GATE_ENABLE 0
#define MAX_QUARTZ_TOP_ENCODER_PIPE_MAN_CLK_GATE_ENABLE 15
#define MIN_QUARTZ_TOP_ENCODER_PIPE_MAN_CLK_GATE_ENABLE 0

/* Register MULTIPIPE_IDLE_PWR_MAN */
#define QUARTZ_TOP_MULTIPIPE_IDLE_PWR_MAN 0x0044
#define MASK_QUARTZ_TOP_CORE_IDLE   0x00000001
#define SHIFT_QUARTZ_TOP_CORE_IDLE  0
#define REGNUM_QUARTZ_TOP_CORE_IDLE 0x0044
#define SIGNED_QUARTZ_TOP_CORE_IDLE 0
#define MAX_QUARTZ_TOP_CORE_IDLE    1
#define MIN_QUARTZ_TOP_CORE_IDLE    0

/* Register RTM_VALUE */
#define QUARTZ_TOP_RTM_VALUE        0x0064
#define MASK_QUARTZ_TOP_RTM         0x0000FFFF
#define SHIFT_QUARTZ_TOP_RTM        0
#define REGNUM_QUARTZ_TOP_RTM       0x0064
#define SIGNED_QUARTZ_TOP_RTM       0
#define MAX_QUARTZ_TOP_RTM          65535
#define MIN_QUARTZ_TOP_RTM          0

/* Register PROC_DEBUG_MSTR */
#define QUARTZ_TOP_PROC_DEBUG_MSTR  0x0070
#define MASK_QUARTZ_TOP_PROC_MSTR_DBG_GPIO_IN 0x00000003
#define SHIFT_QUARTZ_TOP_PROC_MSTR_DBG_GPIO_IN 0
#define REGNUM_QUARTZ_TOP_PROC_MSTR_DBG_GPIO_IN 0x0070
#define SIGNED_QUARTZ_TOP_PROC_MSTR_DBG_GPIO_IN 0
#define MAX_QUARTZ_TOP_PROC_MSTR_DBG_GPIO_IN 3
#define MIN_QUARTZ_TOP_PROC_MSTR_DBG_GPIO_IN 0

#define MASK_QUARTZ_TOP_PROC_MSTR_DBG_IS_SLAVE 0x00000004
#define SHIFT_QUARTZ_TOP_PROC_MSTR_DBG_IS_SLAVE 2
#define REGNUM_QUARTZ_TOP_PROC_MSTR_DBG_IS_SLAVE 0x0070
#define SIGNED_QUARTZ_TOP_PROC_MSTR_DBG_IS_SLAVE 0
#define MAX_QUARTZ_TOP_PROC_MSTR_DBG_IS_SLAVE 1
#define MIN_QUARTZ_TOP_PROC_MSTR_DBG_IS_SLAVE 0

#define MASK_QUARTZ_TOP_PROC_MSTR_DBG_GPIO_OUT 0x00000018
#define SHIFT_QUARTZ_TOP_PROC_MSTR_DBG_GPIO_OUT 3
#define REGNUM_QUARTZ_TOP_PROC_MSTR_DBG_GPIO_OUT 0x0070
#define SIGNED_QUARTZ_TOP_PROC_MSTR_DBG_GPIO_OUT 0
#define MAX_QUARTZ_TOP_PROC_MSTR_DBG_GPIO_OUT 3
#define MIN_QUARTZ_TOP_PROC_MSTR_DBG_GPIO_OUT 0

/* Register CYCLE_COUNTER */
#define QUARTZ_TOP_CYCLE_COUNTER    0x0110
#define MASK_QUARTZ_TOP_CYCLE_COUNTER 0xFFFFFFFF
#define SHIFT_QUARTZ_TOP_CYCLE_COUNTER 0
#define REGNUM_QUARTZ_TOP_CYCLE_COUNTER 0x0110
#define SIGNED_QUARTZ_TOP_CYCLE_COUNTER 0
#define MAX_QUARTZ_TOP_CYCLE_COUNTER 4294967295
#define MIN_QUARTZ_TOP_CYCLE_COUNTER 0

/* Register CYCLE_COUNTER_CTRL */
#define QUARTZ_TOP_CYCLE_COUNTER_CTRL 0x0114
#define MASK_QUARTZ_TOP_CYCLE_COUNTER_ENABLE 0x00000001
#define SHIFT_QUARTZ_TOP_CYCLE_COUNTER_ENABLE 0
#define REGNUM_QUARTZ_TOP_CYCLE_COUNTER_ENABLE 0x0114
#define SIGNED_QUARTZ_TOP_CYCLE_COUNTER_ENABLE 0
#define MAX_QUARTZ_TOP_CYCLE_COUNTER_ENABLE 1
#define MIN_QUARTZ_TOP_CYCLE_COUNTER_ENABLE 0

/* Register SECURE_CONFIG */
#define QUARTZ_TOP_SECURE_CONFIG    0x0280
#define MASK_QUARTZ_TOP_OUTPUT_SECURE_PIPE(i) (0x00000001 << (0 + ((i) * 1)))
#define SHIFT_QUARTZ_TOP_OUTPUT_SECURE_PIPE(i) (0 + ((i) * 1))
#define REGNUM_QUARTZ_TOP_OUTPUT_SECURE_PIPE(i) 0x0280
#define MAX_QUARTZ_TOP_OUTPUT_SECURE_PIPE 1
#define MIN_QUARTZ_TOP_OUTPUT_SECURE_PIPE 0

#define MASK_QUARTZ_TOP_INPUT_SECURE_PIPE(i) (0x00000001 << (8 + ((i) * 1)))
#define SHIFT_QUARTZ_TOP_INPUT_SECURE_PIPE(i) (8 + ((i) * 1))
#define REGNUM_QUARTZ_TOP_INPUT_SECURE_PIPE(i) 0x0280
#define MAX_QUARTZ_TOP_INPUT_SECURE_PIPE 1
#define MIN_QUARTZ_TOP_INPUT_SECURE_PIPE 0

#define MASK_QUARTZ_TOP_DMAC_SECURE 0x01000000
#define SHIFT_QUARTZ_TOP_DMAC_SECURE 24
#define REGNUM_QUARTZ_TOP_DMAC_SECURE 0x0280
#define SIGNED_QUARTZ_TOP_DMAC_SECURE 0
#define MAX_QUARTZ_TOP_DMAC_SECURE  1
#define MIN_QUARTZ_TOP_DMAC_SECURE  0

#define MASK_QUARTZ_TOP_PROC_SECURE 0x10000000
#define SHIFT_QUARTZ_TOP_PROC_SECURE 28
#define REGNUM_QUARTZ_TOP_PROC_SECURE 0x0280
#define SIGNED_QUARTZ_TOP_PROC_SECURE 0
#define MAX_QUARTZ_TOP_PROC_SECURE  1
#define MIN_QUARTZ_TOP_PROC_SECURE  0

/* Register FRAME_COUNTER_ALARM */
#define QUARTZ_TOP_FRAME_COUNTER_ALARM 0x0390
#define MASK_QUARTZ_TOP_LINE_ALARM  0x00001FFF
#define SHIFT_QUARTZ_TOP_LINE_ALARM 0
#define REGNUM_QUARTZ_TOP_LINE_ALARM 0x0390
#define SIGNED_QUARTZ_TOP_LINE_ALARM 0
#define MAX_QUARTZ_TOP_LINE_ALARM   8191
#define MIN_QUARTZ_TOP_LINE_ALARM   0

#define MASK_QUARTZ_TOP_FRAME_ALARM 0x1FFF0000
#define SHIFT_QUARTZ_TOP_FRAME_ALARM 16
#define REGNUM_QUARTZ_TOP_FRAME_ALARM 0x0390
#define SIGNED_QUARTZ_TOP_FRAME_ALARM 0
#define MAX_QUARTZ_TOP_FRAME_ALARM  8191
#define MIN_QUARTZ_TOP_FRAME_ALARM  0

/* Register FRAME_COUNTER */
#define QUARTZ_TOP_FRAME_COUNTER    0x0394
#define MASK_QUARTZ_TOP_LINE_COUNTER 0x00001FFF
#define SHIFT_QUARTZ_TOP_LINE_COUNTER 0
#define REGNUM_QUARTZ_TOP_LINE_COUNTER 0x0394
#define SIGNED_QUARTZ_TOP_LINE_COUNTER 0
#define MAX_QUARTZ_TOP_LINE_COUNTER 8191
#define MIN_QUARTZ_TOP_LINE_COUNTER 0

#define MASK_QUARTZ_TOP_FRAME_COUNTER 0x1FFF0000
#define SHIFT_QUARTZ_TOP_FRAME_COUNTER 16
#define REGNUM_QUARTZ_TOP_FRAME_COUNTER 0x0394
#define SIGNED_QUARTZ_TOP_FRAME_COUNTER 0
#define MAX_QUARTZ_TOP_FRAME_COUNTER 8191
#define MIN_QUARTZ_TOP_FRAME_COUNTER 0

/* Register QUARTZ_CORE_ID */
#define QUARTZ_TOP_QUARTZ_CORE_ID   0x03C0
#define MASK_QUARTZ_TOP_QUARTZ_CORE_CONFIG 0x0000FFFF
#define SHIFT_QUARTZ_TOP_QUARTZ_CORE_CONFIG 0
#define REGNUM_QUARTZ_TOP_QUARTZ_CORE_CONFIG 0x03C0
#define SIGNED_QUARTZ_TOP_QUARTZ_CORE_CONFIG 0
#define MAX_QUARTZ_TOP_QUARTZ_CORE_CONFIG 65535
#define MIN_QUARTZ_TOP_QUARTZ_CORE_CONFIG 0

#define MASK_QUARTZ_TOP_QUARTZ_CORE_ID 0x00FF0000
#define SHIFT_QUARTZ_TOP_QUARTZ_CORE_ID 16
#define REGNUM_QUARTZ_TOP_QUARTZ_CORE_ID 0x03C0
#define SIGNED_QUARTZ_TOP_QUARTZ_CORE_ID 0
#define MAX_QUARTZ_TOP_QUARTZ_CORE_ID 255
#define MIN_QUARTZ_TOP_QUARTZ_CORE_ID 0

#define MASK_QUARTZ_TOP_QUARTZ_GROUP_ID 0xFF000000
#define SHIFT_QUARTZ_TOP_QUARTZ_GROUP_ID 24
#define REGNUM_QUARTZ_TOP_QUARTZ_GROUP_ID 0x03C0
#define SIGNED_QUARTZ_TOP_QUARTZ_GROUP_ID 0
#define MAX_QUARTZ_TOP_QUARTZ_GROUP_ID 255
#define MIN_QUARTZ_TOP_QUARTZ_GROUP_ID 0

/* Register QUARTZ_CORE_REV */
#define QUARTZ_TOP_QUARTZ_CORE_REV  0x03D0
#define MASK_QUARTZ_TOP_QUARTZ_MAINT_REV 0x000000FF
#define SHIFT_QUARTZ_TOP_QUARTZ_MAINT_REV 0
#define REGNUM_QUARTZ_TOP_QUARTZ_MAINT_REV 0x03D0
#define SIGNED_QUARTZ_TOP_QUARTZ_MAINT_REV 0
#define MAX_QUARTZ_TOP_QUARTZ_MAINT_REV 255
#define MIN_QUARTZ_TOP_QUARTZ_MAINT_REV 0

#define MASK_QUARTZ_TOP_QUARTZ_MINOR_REV 0x0000FF00
#define SHIFT_QUARTZ_TOP_QUARTZ_MINOR_REV 8
#define REGNUM_QUARTZ_TOP_QUARTZ_MINOR_REV 0x03D0
#define SIGNED_QUARTZ_TOP_QUARTZ_MINOR_REV 0
#define MAX_QUARTZ_TOP_QUARTZ_MINOR_REV 255
#define MIN_QUARTZ_TOP_QUARTZ_MINOR_REV 0

#define MASK_QUARTZ_TOP_QUARTZ_MAJOR_REV 0x00FF0000
#define SHIFT_QUARTZ_TOP_QUARTZ_MAJOR_REV 16
#define REGNUM_QUARTZ_TOP_QUARTZ_MAJOR_REV 0x03D0
#define SIGNED_QUARTZ_TOP_QUARTZ_MAJOR_REV 0
#define MAX_QUARTZ_TOP_QUARTZ_MAJOR_REV 255
#define MIN_QUARTZ_TOP_QUARTZ_MAJOR_REV 0

#define MASK_QUARTZ_TOP_QUARTZ_DESIGNER 0xFF000000
#define SHIFT_QUARTZ_TOP_QUARTZ_DESIGNER 24
#define REGNUM_QUARTZ_TOP_QUARTZ_DESIGNER 0x03D0
#define SIGNED_QUARTZ_TOP_QUARTZ_DESIGNER 0
#define MAX_QUARTZ_TOP_QUARTZ_DESIGNER 255
#define MIN_QUARTZ_TOP_QUARTZ_DESIGNER 0

/* Register QUARTZ_CONFIG */
#define QUARTZ_TOP_QUARTZ_CONFIG    0x03E0
#define MASK_QUARTZ_TOP_QUARTZ_NUM_ENCODER_PIPES 0x00000007
#define SHIFT_QUARTZ_TOP_QUARTZ_NUM_ENCODER_PIPES 0
#define REGNUM_QUARTZ_TOP_QUARTZ_NUM_ENCODER_PIPES 0x03E0
#define SIGNED_QUARTZ_TOP_QUARTZ_NUM_ENCODER_PIPES 0
#define MAX_QUARTZ_TOP_QUARTZ_NUM_ENCODER_PIPES 7
#define MIN_QUARTZ_TOP_QUARTZ_NUM_ENCODER_PIPES 0

#define MASK_QUARTZ_TOP_QUARTZ_AVC_SUPPORTED 0x00000010
#define SHIFT_QUARTZ_TOP_QUARTZ_AVC_SUPPORTED 4
#define REGNUM_QUARTZ_TOP_QUARTZ_AVC_SUPPORTED 0x03E0
#define SIGNED_QUARTZ_TOP_QUARTZ_AVC_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_AVC_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_AVC_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_HEVC_SUPPORTED 0x00000020
#define SHIFT_QUARTZ_TOP_QUARTZ_HEVC_SUPPORTED 5
#define REGNUM_QUARTZ_TOP_QUARTZ_HEVC_SUPPORTED 0x03E0
#define SIGNED_QUARTZ_TOP_QUARTZ_HEVC_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_HEVC_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_HEVC_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_FE_HARDWARE_INPUT_PIXELS 0x0000E000
#define SHIFT_QUARTZ_TOP_QUARTZ_FE_HARDWARE_INPUT_PIXELS 13
#define REGNUM_QUARTZ_TOP_QUARTZ_FE_HARDWARE_INPUT_PIXELS 0x03E0
#define SIGNED_QUARTZ_TOP_QUARTZ_FE_HARDWARE_INPUT_PIXELS 0
#define MAX_QUARTZ_TOP_QUARTZ_FE_HARDWARE_INPUT_PIXELS 7
#define MIN_QUARTZ_TOP_QUARTZ_FE_HARDWARE_INPUT_PIXELS 0

#define MASK_QUARTZ_TOP_QUARTZ_FE_HARDWARE_INPUT_BLOCK 0x00010000
#define SHIFT_QUARTZ_TOP_QUARTZ_FE_HARDWARE_INPUT_BLOCK 16
#define REGNUM_QUARTZ_TOP_QUARTZ_FE_HARDWARE_INPUT_BLOCK 0x03E0
#define SIGNED_QUARTZ_TOP_QUARTZ_FE_HARDWARE_INPUT_BLOCK 0
#define MAX_QUARTZ_TOP_QUARTZ_FE_HARDWARE_INPUT_BLOCK 1
#define MIN_QUARTZ_TOP_QUARTZ_FE_HARDWARE_INPUT_BLOCK 0

#define MASK_QUARTZ_TOP_QUARTZ_FE_LINE_STORE_SUPPORTED 0x00020000
#define SHIFT_QUARTZ_TOP_QUARTZ_FE_LINE_STORE_SUPPORTED 17
#define REGNUM_QUARTZ_TOP_QUARTZ_FE_LINE_STORE_SUPPORTED 0x03E0
#define SIGNED_QUARTZ_TOP_QUARTZ_FE_LINE_STORE_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_FE_LINE_STORE_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_FE_LINE_STORE_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_FE_10BIT_SUPPORTED 0x00040000
#define SHIFT_QUARTZ_TOP_QUARTZ_FE_10BIT_SUPPORTED 18
#define REGNUM_QUARTZ_TOP_QUARTZ_FE_10BIT_SUPPORTED 0x03E0
#define SIGNED_QUARTZ_TOP_QUARTZ_FE_10BIT_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_FE_10BIT_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_FE_10BIT_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_FE_COLOUR_SPACE_CONV_SUPPORTED 0x00080000
#define SHIFT_QUARTZ_TOP_QUARTZ_FE_COLOUR_SPACE_CONV_SUPPORTED 19
#define REGNUM_QUARTZ_TOP_QUARTZ_FE_COLOUR_SPACE_CONV_SUPPORTED 0x03E0
#define SIGNED_QUARTZ_TOP_QUARTZ_FE_COLOUR_SPACE_CONV_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_FE_COLOUR_SPACE_CONV_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_FE_COLOUR_SPACE_CONV_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_FE_565_COLOUR_SPACE_CONV_SUPPORTED 0x00100000
#define SHIFT_QUARTZ_TOP_QUARTZ_FE_565_COLOUR_SPACE_CONV_SUPPORTED 20
#define REGNUM_QUARTZ_TOP_QUARTZ_FE_565_COLOUR_SPACE_CONV_SUPPORTED 0x03E0
#define SIGNED_QUARTZ_TOP_QUARTZ_FE_565_COLOUR_SPACE_CONV_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_FE_565_COLOUR_SPACE_CONV_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_FE_565_COLOUR_SPACE_CONV_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_FE_SCALING_SUPPORTED 0x00200000
#define SHIFT_QUARTZ_TOP_QUARTZ_FE_SCALING_SUPPORTED 21
#define REGNUM_QUARTZ_TOP_QUARTZ_FE_SCALING_SUPPORTED 0x03E0
#define SIGNED_QUARTZ_TOP_QUARTZ_FE_SCALING_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_FE_SCALING_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_FE_SCALING_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_ENCODE_10BIT_SUPPORTED 0x01000000
#define SHIFT_QUARTZ_TOP_QUARTZ_ENCODE_10BIT_SUPPORTED 24
#define REGNUM_QUARTZ_TOP_QUARTZ_ENCODE_10BIT_SUPPORTED 0x03E0
#define SIGNED_QUARTZ_TOP_QUARTZ_ENCODE_10BIT_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_ENCODE_10BIT_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_ENCODE_10BIT_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_422_SUPPORTED 0x02000000
#define SHIFT_QUARTZ_TOP_QUARTZ_422_SUPPORTED 25
#define REGNUM_QUARTZ_TOP_QUARTZ_422_SUPPORTED 0x03E0
#define SIGNED_QUARTZ_TOP_QUARTZ_422_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_422_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_422_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_444_SUPPORTED 0x04000000
#define SHIFT_QUARTZ_TOP_QUARTZ_444_SUPPORTED 26
#define REGNUM_QUARTZ_TOP_QUARTZ_444_SUPPORTED 0x03E0
#define SIGNED_QUARTZ_TOP_QUARTZ_444_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_444_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_444_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_MAX_CTU_SIZE_SUPPORTED 0xC0000000
#define SHIFT_QUARTZ_TOP_QUARTZ_MAX_CTU_SIZE_SUPPORTED 30
#define REGNUM_QUARTZ_TOP_QUARTZ_MAX_CTU_SIZE_SUPPORTED 0x03E0
#define SIGNED_QUARTZ_TOP_QUARTZ_MAX_CTU_SIZE_SUPPORTED 0
#define QUARTZ_TOP_QUARTZ_MAX_CTU_SIZE_SUPPORTED_MAX_CTU_16X16		0x00000001		/* 16x16 CTU size supported */
#define QUARTZ_TOP_QUARTZ_MAX_CTU_SIZE_SUPPORTED_MAX_CTU_32X32		0x00000002		/* 32x32 CTU size and smaller supported */
#define QUARTZ_TOP_QUARTZ_MAX_CTU_SIZE_SUPPORTED_MAX_CTU_64X64		0x00000003		/* 64x64 CTU size and smaller supported */
#define MAX_QUARTZ_TOP_QUARTZ_MAX_CTU_SIZE_SUPPORTED 3
#define MIN_QUARTZ_TOP_QUARTZ_MAX_CTU_SIZE_SUPPORTED 0

/* Register QUARTZ_CONFIG_2 */
#define QUARTZ_TOP_QUARTZ_CONFIG_2  0x03E4
#define MASK_QUARTZ_TOP_QUARTZ_LOG2_MAX_PICTURE_WIDTH 0x0000000F
#define SHIFT_QUARTZ_TOP_QUARTZ_LOG2_MAX_PICTURE_WIDTH 0
#define REGNUM_QUARTZ_TOP_QUARTZ_LOG2_MAX_PICTURE_WIDTH 0x03E4
#define SIGNED_QUARTZ_TOP_QUARTZ_LOG2_MAX_PICTURE_WIDTH 0
#define MAX_QUARTZ_TOP_QUARTZ_LOG2_MAX_PICTURE_WIDTH 15
#define MIN_QUARTZ_TOP_QUARTZ_LOG2_MAX_PICTURE_WIDTH 0

#define MASK_QUARTZ_TOP_QUARTZ_LOG2_MAX_PICTURE_HEIGHT 0x000000F0
#define SHIFT_QUARTZ_TOP_QUARTZ_LOG2_MAX_PICTURE_HEIGHT 4
#define REGNUM_QUARTZ_TOP_QUARTZ_LOG2_MAX_PICTURE_HEIGHT 0x03E4
#define SIGNED_QUARTZ_TOP_QUARTZ_LOG2_MAX_PICTURE_HEIGHT 0
#define MAX_QUARTZ_TOP_QUARTZ_LOG2_MAX_PICTURE_HEIGHT 15
#define MIN_QUARTZ_TOP_QUARTZ_LOG2_MAX_PICTURE_HEIGHT 0

#define MASK_QUARTZ_TOP_QUARTZ_REF_CACHE_TILE_GROUP_WIDTH 0x00000F00
#define SHIFT_QUARTZ_TOP_QUARTZ_REF_CACHE_TILE_GROUP_WIDTH 8
#define REGNUM_QUARTZ_TOP_QUARTZ_REF_CACHE_TILE_GROUP_WIDTH 0x03E4
#define SIGNED_QUARTZ_TOP_QUARTZ_REF_CACHE_TILE_GROUP_WIDTH 0
#define MAX_QUARTZ_TOP_QUARTZ_REF_CACHE_TILE_GROUP_WIDTH 15
#define MIN_QUARTZ_TOP_QUARTZ_REF_CACHE_TILE_GROUP_WIDTH 0

#define MASK_QUARTZ_TOP_QUARTZ_REF_CACHE_TILE_GROUP_HEIGHT 0x0000F000
#define SHIFT_QUARTZ_TOP_QUARTZ_REF_CACHE_TILE_GROUP_HEIGHT 12
#define REGNUM_QUARTZ_TOP_QUARTZ_REF_CACHE_TILE_GROUP_HEIGHT 0x03E4
#define SIGNED_QUARTZ_TOP_QUARTZ_REF_CACHE_TILE_GROUP_HEIGHT 0
#define MAX_QUARTZ_TOP_QUARTZ_REF_CACHE_TILE_GROUP_HEIGHT 15
#define MIN_QUARTZ_TOP_QUARTZ_REF_CACHE_TILE_GROUP_HEIGHT 0

#define MASK_QUARTZ_TOP_QUARTZ_REF_CACHE_N_ASSOCIATIVITY 0x000F0000
#define SHIFT_QUARTZ_TOP_QUARTZ_REF_CACHE_N_ASSOCIATIVITY 16
#define REGNUM_QUARTZ_TOP_QUARTZ_REF_CACHE_N_ASSOCIATIVITY 0x03E4
#define SIGNED_QUARTZ_TOP_QUARTZ_REF_CACHE_N_ASSOCIATIVITY 0
#define MAX_QUARTZ_TOP_QUARTZ_REF_CACHE_N_ASSOCIATIVITY 15
#define MIN_QUARTZ_TOP_QUARTZ_REF_CACHE_N_ASSOCIATIVITY 0

#define MASK_QUARTZ_TOP_QUARTZ_REF_CACHE_RAM_DEPTH_DIV16 0x1FF00000
#define SHIFT_QUARTZ_TOP_QUARTZ_REF_CACHE_RAM_DEPTH_DIV16 20
#define NBITS_QUARTZ_TOP_QUARTZ_REF_CACHE_RAM_DEPTH_DIV16 9
#define REGNUM_QUARTZ_TOP_QUARTZ_REF_CACHE_RAM_DEPTH_DIV16 0x03E4
#define SIGNED_QUARTZ_TOP_QUARTZ_REF_CACHE_RAM_DEPTH_DIV16 0
#define MAX_QUARTZ_TOP_QUARTZ_REF_CACHE_RAM_DEPTH_DIV16 511
#define MIN_QUARTZ_TOP_QUARTZ_REF_CACHE_RAM_DEPTH_DIV16 0

#define MASK_QUARTZ_TOP_QUARTZ_REF_CACHE_LINESTORE_SUPPORTED 0x20000000
#define SHIFT_QUARTZ_TOP_QUARTZ_REF_CACHE_LINESTORE_SUPPORTED 29
#define NBITS_QUARTZ_TOP_QUARTZ_REF_CACHE_LINESTORE_SUPPORTED 1
#define REGNUM_QUARTZ_TOP_QUARTZ_REF_CACHE_LINESTORE_SUPPORTED 0x03E4
#define SIGNED_QUARTZ_TOP_QUARTZ_REF_CACHE_LINESTORE_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_REF_CACHE_LINESTORE_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_REF_CACHE_LINESTORE_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_NUM_REF_PIC_SUPPORTED 0xC0000000
#define SHIFT_QUARTZ_TOP_QUARTZ_NUM_REF_PIC_SUPPORTED 30
#define REGNUM_QUARTZ_TOP_QUARTZ_NUM_REF_PIC_SUPPORTED 0x03E4
#define SIGNED_QUARTZ_TOP_QUARTZ_NUM_REF_PIC_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_NUM_REF_PIC_SUPPORTED 3
#define MIN_QUARTZ_TOP_QUARTZ_NUM_REF_PIC_SUPPORTED 0

/* Register QUARTZ_CONFIG_3 */
#define QUARTZ_TOP_QUARTZ_CONFIG_3  0x03E8
#define MASK_QUARTZ_TOP_QUARTZ_WEIGHTED_PRED_SUPPORTED 0x00000001
#define SHIFT_QUARTZ_TOP_QUARTZ_WEIGHTED_PRED_SUPPORTED 0
#define REGNUM_QUARTZ_TOP_QUARTZ_WEIGHTED_PRED_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_WEIGHTED_PRED_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_WEIGHTED_PRED_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_WEIGHTED_PRED_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_IME_SUB_8X8_PU_SUPPORTED 0x00000002
#define SHIFT_QUARTZ_TOP_QUARTZ_IME_SUB_8X8_PU_SUPPORTED 1
#define REGNUM_QUARTZ_TOP_QUARTZ_IME_SUB_8X8_PU_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_IME_SUB_8X8_PU_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_IME_SUB_8X8_PU_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_IME_SUB_8X8_PU_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_FME_NUM_PRED_MIN1 0x00000004
#define SHIFT_QUARTZ_TOP_QUARTZ_FME_NUM_PRED_MIN1 2
#define REGNUM_QUARTZ_TOP_QUARTZ_FME_NUM_PRED_MIN1 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_FME_NUM_PRED_MIN1 0
#define MAX_QUARTZ_TOP_QUARTZ_FME_NUM_PRED_MIN1 1
#define MIN_QUARTZ_TOP_QUARTZ_FME_NUM_PRED_MIN1 0

#define MASK_QUARTZ_TOP_QUARTZ_FME_QUARTER_PEL_SUPPORTED 0x00000008
#define SHIFT_QUARTZ_TOP_QUARTZ_FME_QUARTER_PEL_SUPPORTED 3
#define REGNUM_QUARTZ_TOP_QUARTZ_FME_QUARTER_PEL_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_FME_QUARTER_PEL_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_FME_QUARTER_PEL_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_FME_QUARTER_PEL_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_ED_4X4_SUPPORTED 0x00000010
#define SHIFT_QUARTZ_TOP_QUARTZ_ED_4X4_SUPPORTED 4
#define REGNUM_QUARTZ_TOP_QUARTZ_ED_4X4_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_ED_4X4_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_ED_4X4_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_ED_4X4_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_ED_8X8_SUPPORTED 0x00000020
#define SHIFT_QUARTZ_TOP_QUARTZ_ED_8X8_SUPPORTED 5
#define REGNUM_QUARTZ_TOP_QUARTZ_ED_8X8_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_ED_8X8_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_ED_8X8_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_ED_8X8_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_ED_16X16_SUPPORTED 0x00000040
#define SHIFT_QUARTZ_TOP_QUARTZ_ED_16X16_SUPPORTED 6
#define REGNUM_QUARTZ_TOP_QUARTZ_ED_16X16_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_ED_16X16_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_ED_16X16_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_ED_16X16_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_ED_32X32_SUPPORTED 0x00000080
#define SHIFT_QUARTZ_TOP_QUARTZ_ED_32X32_SUPPORTED 7
#define REGNUM_QUARTZ_TOP_QUARTZ_ED_32X32_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_ED_32X32_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_ED_32X32_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_ED_32X32_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_CUSTOM_QUANT_SUPPORTED 0x00000100
#define SHIFT_QUARTZ_TOP_QUARTZ_CUSTOM_QUANT_SUPPORTED 8
#define REGNUM_QUARTZ_TOP_QUARTZ_CUSTOM_QUANT_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_CUSTOM_QUANT_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_CUSTOM_QUANT_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_CUSTOM_QUANT_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_ADAPTIVE_ROUND_SUPPORTED 0x00000200
#define SHIFT_QUARTZ_TOP_QUARTZ_ADAPTIVE_ROUND_SUPPORTED 9
#define REGNUM_QUARTZ_TOP_QUARTZ_ADAPTIVE_ROUND_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_ADAPTIVE_ROUND_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_ADAPTIVE_ROUND_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_ADAPTIVE_ROUND_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_VCM_SUPPORTED 0x00000400
#define SHIFT_QUARTZ_TOP_QUARTZ_VCM_SUPPORTED 10
#define REGNUM_QUARTZ_TOP_QUARTZ_VCM_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_VCM_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_VCM_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_VCM_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_LOSSLESS_SUPPORTED 0x00001000
#define SHIFT_QUARTZ_TOP_QUARTZ_LOSSLESS_SUPPORTED 12
#define NBITS_QUARTZ_TOP_QUARTZ_LOSSLESS_SUPPORTED 1
#define REGNUM_QUARTZ_TOP_QUARTZ_LOSSLESS_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_LOSSLESS_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_LOSSLESS_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_LOSSLESS_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_AVC_FIELD_CODING_SUPPORTED 0x00002000
#define SHIFT_QUARTZ_TOP_QUARTZ_AVC_FIELD_CODING_SUPPORTED 13
#define NBITS_QUARTZ_TOP_QUARTZ_AVC_FIELD_CODING_SUPPORTED 1
#define REGNUM_QUARTZ_TOP_QUARTZ_AVC_FIELD_CODING_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_AVC_FIELD_CODING_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_AVC_FIELD_CODING_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_AVC_FIELD_CODING_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_CONSTRAINED_INTRA_SUPPORTED 0x00004000
#define SHIFT_QUARTZ_TOP_QUARTZ_CONSTRAINED_INTRA_SUPPORTED 14
#define NBITS_QUARTZ_TOP_QUARTZ_CONSTRAINED_INTRA_SUPPORTED 1
#define REGNUM_QUARTZ_TOP_QUARTZ_CONSTRAINED_INTRA_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_CONSTRAINED_INTRA_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_CONSTRAINED_INTRA_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_CONSTRAINED_INTRA_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_MV_SEED_SUPPORTED 0x00008000
#define SHIFT_QUARTZ_TOP_QUARTZ_MV_SEED_SUPPORTED 15
#define NBITS_QUARTZ_TOP_QUARTZ_MV_SEED_SUPPORTED 1
#define REGNUM_QUARTZ_TOP_QUARTZ_MV_SEED_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_MV_SEED_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_MV_SEED_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_MV_SEED_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_SAO_SUPPORTED 0x00010000
#define SHIFT_QUARTZ_TOP_QUARTZ_SAO_SUPPORTED 16
#define REGNUM_QUARTZ_TOP_QUARTZ_SAO_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_SAO_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_SAO_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_SAO_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_INLOOP_TILE_FILTER_SUPPORTED 0x00020000
#define SHIFT_QUARTZ_TOP_QUARTZ_INLOOP_TILE_FILTER_SUPPORTED 17
#define REGNUM_QUARTZ_TOP_QUARTZ_INLOOP_TILE_FILTER_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_INLOOP_TILE_FILTER_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_INLOOP_TILE_FILTER_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_INLOOP_TILE_FILTER_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_STREAM_HARDWARE_OUTPUT_SUPPORTED 0x00080000
#define SHIFT_QUARTZ_TOP_QUARTZ_STREAM_HARDWARE_OUTPUT_SUPPORTED 19
#define NBITS_QUARTZ_TOP_QUARTZ_STREAM_HARDWARE_OUTPUT_SUPPORTED 1
#define REGNUM_QUARTZ_TOP_QUARTZ_STREAM_HARDWARE_OUTPUT_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_STREAM_HARDWARE_OUTPUT_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_STREAM_HARDWARE_OUTPUT_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_STREAM_HARDWARE_OUTPUT_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_ENTROPY_AVC_CAVLC_SUPPORTED 0x00100000
#define SHIFT_QUARTZ_TOP_QUARTZ_ENTROPY_AVC_CAVLC_SUPPORTED 20
#define REGNUM_QUARTZ_TOP_QUARTZ_ENTROPY_AVC_CAVLC_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_ENTROPY_AVC_CAVLC_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_ENTROPY_AVC_CAVLC_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_ENTROPY_AVC_CAVLC_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_ENTROPY_AVC_CABAC_SUPPORTED 0x00200000
#define SHIFT_QUARTZ_TOP_QUARTZ_ENTROPY_AVC_CABAC_SUPPORTED 21
#define REGNUM_QUARTZ_TOP_QUARTZ_ENTROPY_AVC_CABAC_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_ENTROPY_AVC_CABAC_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_ENTROPY_AVC_CABAC_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_ENTROPY_AVC_CABAC_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_ENTROPY_STREAM_BUFFER_MANAGEMENT_SUPPORTED 0x00400000
#define SHIFT_QUARTZ_TOP_QUARTZ_ENTROPY_STREAM_BUFFER_MANAGEMENT_SUPPORTED 22
#define REGNUM_QUARTZ_TOP_QUARTZ_ENTROPY_STREAM_BUFFER_MANAGEMENT_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_ENTROPY_STREAM_BUFFER_MANAGEMENT_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_ENTROPY_STREAM_BUFFER_MANAGEMENT_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_ENTROPY_STREAM_BUFFER_MANAGEMENT_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_HEVC_DEPENDENT_SLICE_SUPPORTED 0x01000000
#define SHIFT_QUARTZ_TOP_QUARTZ_HEVC_DEPENDENT_SLICE_SUPPORTED 24
#define NBITS_QUARTZ_TOP_QUARTZ_HEVC_DEPENDENT_SLICE_SUPPORTED 1
#define REGNUM_QUARTZ_TOP_QUARTZ_HEVC_DEPENDENT_SLICE_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_HEVC_DEPENDENT_SLICE_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_HEVC_DEPENDENT_SLICE_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_HEVC_DEPENDENT_SLICE_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_WAVEFRONT_PIPES_SUPPORTED 0x02000000
#define SHIFT_QUARTZ_TOP_QUARTZ_WAVEFRONT_PIPES_SUPPORTED 25
#define NBITS_QUARTZ_TOP_QUARTZ_WAVEFRONT_PIPES_SUPPORTED 1
#define REGNUM_QUARTZ_TOP_QUARTZ_WAVEFRONT_PIPES_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_WAVEFRONT_PIPES_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_WAVEFRONT_PIPES_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_WAVEFRONT_PIPES_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_TILE_COLUMN_SUPPORTED 0x04000000
#define SHIFT_QUARTZ_TOP_QUARTZ_TILE_COLUMN_SUPPORTED 26
#define NBITS_QUARTZ_TOP_QUARTZ_TILE_COLUMN_SUPPORTED 1
#define REGNUM_QUARTZ_TOP_QUARTZ_TILE_COLUMN_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_TILE_COLUMN_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_TILE_COLUMN_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_TILE_COLUMN_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_MC_CARC_SUPPORTED 0x10000000
#define SHIFT_QUARTZ_TOP_QUARTZ_MC_CARC_SUPPORTED 28
#define NBITS_QUARTZ_TOP_QUARTZ_MC_CARC_SUPPORTED 1
#define REGNUM_QUARTZ_TOP_QUARTZ_MC_CARC_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_MC_CARC_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_MC_CARC_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_MC_CARC_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_FBC_SUPPORTED 0x40000000
#define SHIFT_QUARTZ_TOP_QUARTZ_FBC_SUPPORTED 30
#define NBITS_QUARTZ_TOP_QUARTZ_FBC_SUPPORTED 1
#define REGNUM_QUARTZ_TOP_QUARTZ_FBC_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_FBC_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_FBC_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_FBC_SUPPORTED 0

#define MASK_QUARTZ_TOP_QUARTZ_FBC_SOURCE_FRAME_SUPPORTED 0x80000000
#define SHIFT_QUARTZ_TOP_QUARTZ_FBC_SOURCE_FRAME_SUPPORTED 31
#define NBITS_QUARTZ_TOP_QUARTZ_FBC_SOURCE_FRAME_SUPPORTED 1
#define REGNUM_QUARTZ_TOP_QUARTZ_FBC_SOURCE_FRAME_SUPPORTED 0x03E8
#define SIGNED_QUARTZ_TOP_QUARTZ_FBC_SOURCE_FRAME_SUPPORTED 0
#define MAX_QUARTZ_TOP_QUARTZ_FBC_SOURCE_FRAME_SUPPORTED 1
#define MIN_QUARTZ_TOP_QUARTZ_FBC_SOURCE_FRAME_SUPPORTED 0

/* Register QUARTZ_PROC_CONFIG */
#define QUARTZ_TOP_QUARTZ_PROC_CONFIG 0x03EC
#define MASK_QUARTZ_TOP_LTP_INSTRUCTION_RAM_SIZE 0x000000FF
#define SHIFT_QUARTZ_TOP_LTP_INSTRUCTION_RAM_SIZE 0
#define REGNUM_QUARTZ_TOP_LTP_INSTRUCTION_RAM_SIZE 0x03EC
#define SIGNED_QUARTZ_TOP_LTP_INSTRUCTION_RAM_SIZE 0
#define MAX_QUARTZ_TOP_LTP_INSTRUCTION_RAM_SIZE 255
#define MIN_QUARTZ_TOP_LTP_INSTRUCTION_RAM_SIZE 0

#define MASK_QUARTZ_TOP_LTP_DATA_RAM_SIZE 0x0000FF00
#define SHIFT_QUARTZ_TOP_LTP_DATA_RAM_SIZE 8
#define REGNUM_QUARTZ_TOP_LTP_DATA_RAM_SIZE 0x03EC
#define SIGNED_QUARTZ_TOP_LTP_DATA_RAM_SIZE 0
#define MAX_QUARTZ_TOP_LTP_DATA_RAM_SIZE 255
#define MIN_QUARTZ_TOP_LTP_DATA_RAM_SIZE 0

/* Register QUARTZ_LINE_STORE_CONFIG */
#define QUARTZ_TOP_QUARTZ_LINE_STORE_CONFIG 0x03F0
#define MASK_QUARTZ_TOP_INTRA_LINE_STORE_WIDTH 0x000000FF
#define SHIFT_QUARTZ_TOP_INTRA_LINE_STORE_WIDTH 0
#define REGNUM_QUARTZ_TOP_INTRA_LINE_STORE_WIDTH 0x03F0
#define SIGNED_QUARTZ_TOP_INTRA_LINE_STORE_WIDTH 0
#define MAX_QUARTZ_TOP_INTRA_LINE_STORE_WIDTH 255
#define MIN_QUARTZ_TOP_INTRA_LINE_STORE_WIDTH 0

#define MASK_QUARTZ_TOP_INTER_LINE_STORE_WIDTH 0x0000FF00
#define SHIFT_QUARTZ_TOP_INTER_LINE_STORE_WIDTH 8
#define REGNUM_QUARTZ_TOP_INTER_LINE_STORE_WIDTH 0x03F0
#define SIGNED_QUARTZ_TOP_INTER_LINE_STORE_WIDTH 0
#define MAX_QUARTZ_TOP_INTER_LINE_STORE_WIDTH 255
#define MIN_QUARTZ_TOP_INTER_LINE_STORE_WIDTH 0

