KBUILD_CFLAGS  +=  -I$(srctree)/$(src)/.. -I$(srctree)/$(src)/x86emu/include -DIN_MODULE

obj-y := int15.o int16.o int1a.o init.o helper_exec.o helper_mem.o pci-iface.o

obj-y += x86emu/src/x86emu/


