KBUILD_CFLAGS  +=  -I$(obj)/.. -I$(obj)/x86emu/include -DIN_MODULE

obj-y := int10.o int15.o int16.o int1a.o \
	inte6.o init.o helper_exec.o helper_mem.o \
	pci-iface.o

obj-y += x86emu/src/x86emu/


