
#
# l/Makefile
#
# This file is included by the Elbrus arches makefile to support common
# features of the architecture
#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#

obj-y				+= kernel/
