# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2023 MCST

#
# l/Makefile
#
# This file is included by the Elbrus arches makefile to support common
# features of the architecture
#

obj-y				+= kernel/
