 # SPDX-License-Identifier: GPL-2.0
 # Copyright (c) 2023 MCST
 
#
# Makefile for MMRM Controller - new driver
#

mmrse-objs := mmrse_dev.o mmrse_dev_bc.o mmrse_dev_rt.o mmrse_dev_bm.o mmrse_debugfs.o mmrse_main.o

obj-$(CONFIG_MMRSE) := mmrse.o
