override TARGET_PRIMARY_ARCH := target_e2k
override TARGET_SECONDARY_ARCH := 
override TARGET_ALL_ARCH :=  target_e2k 
override TARGET_FORCE_32BIT := 
override KERNEL_COMPONENTS := srvkm e2c3_gpu
override KERNEL_CROSS_COMPILE := e2k-linux-
override PVRSRV_MODNAME := pvrsrvkm
override PVR_BUILD_DIR := e2c3_gpu
override PVR_BUILD_TYPE := release
override PVR_SYSTEM := e2c3_gpu
override PVR_LOADER := 
override BUILD := release
override DEBUGLINK := 1
override VMM_TYPE := stub
override SUPPORT_COMPUTE := 1
override SUPPORT_TLA := 1
override RGX_TIMECORR_CLOCK := mono
override PVR_HANDLE_BACKEND := idr
override SUPPORT_SERVER_SYNC := 1
override SUPPORT_BUFFER_SYNC := 1
