override TARGET_PRIMARY_ARCH := target_e2k
override TARGET_SECONDARY_ARCH :=
override TARGET_ALL_ARCH := target_e2k
override TARGET_FORCE_32BIT :=
override PVR_ARCH := rogue
override KERNEL_COMPONENTS := srvkm e2c3_gpu
override WINDOW_SYSTEM := nulldrmws
override PVRSRV_MODNAME := pvrsrvkm
override PVRSYNC_MODNAME := pvr_sync
override PVR_BUILD_DIR := e2c3_gpu
override PVR_BUILD_TYPE := release
override SUPPORT_RGX := 1
override PVR_SYSTEM := e2c3_gpu
override PVR_LOADER :=
override BUILD := release
override DEBUGLINK := 1
override SUPPORT_PHYSMEM_TEST := 1
override RGX_NUM_OS_SUPPORTED := 1
override VMM_TYPE := stub
override SUPPORT_POWMON_COMPONENT := 1
override RGX_TIMECORR_CLOCK := mono
override PDVFS_COM_HOST := 1
override PDVFS_COM_AP := 2
override PDVFS_COM_PMC := 3
override PDVFS_COM_IMG_CLKDIV := 4
override PDVFS_COM := PDVFS_COM_HOST
override PVR_GPIO_MODE_GENERAL := 1
override PVR_GPIO_MODE_POWMON_PIN := 2
override PVR_GPIO_MODE := PVR_GPIO_MODE_GENERAL
override PVR_HANDLE_BACKEND := idr
override SUPPORT_DMABUF_BRIDGE := 1
override SUPPORT_USC_BREAKPOINT := 1
override SUPPORT_NATIVE_FENCE_SYNC := 1
override SUPPORT_DMA_FENCE := 1
override SUPPORT_BUFFER_SYNC := 1
