#
# Makefile for the RDMA controllers (network device)
#

obj-$(CONFIG_RDMA_NET) += rdma_net.o

rdma_net-objs := rdma_send_msg_net.o rdma_intr_net.o lvnet_net.o get_event_rdma_net.o rdma_proc_init_net.o
