 # SPDX-License-Identifier: GPL-2.0
 # Copyright (c) 2023 MCST
 
#
# Makefile for EPIC (CEPIC, PREPIC, IO-EPIC) drivers
#

obj-$(CONFIG_EPIC)		+= epic.o ipi.o irq.o io_epic.o
obj-$(CONFIG_SMP)		+= smp.o
obj-$(CONFIG_IRQ_WORK)		+= irq_work.o
