#
# Makefile for the Linux kernel device drivers.
#


obj-$(CONFIG_AGAT_NIC)	+= agat-nic.o


agat-nic-objs			:= eeprom.o interrupt.o media.o \
				   timer.o tulip_core.o		\
				   21142.o pnic.o pnic2.o
