 # SPDX-License-Identifier: GPL-2.0
 # Copyright (c) 2023 MCST
 
# __restore_processor_state() restores %gs after S3 resume and so should not
# itself be stack-protected

obj-$(CONFIG_PM_SLEEP)		+= cpu.o
obj-$(CONFIG_HIBERNATION)	+= hibernate.o 
