 # SPDX-License-Identifier: GPL-2.0
 # Copyright (c) 2023 MCST
 
#
# Makefile for XGBE
#

mxgbe-objs := \
	mxgbe_hw.o \
	mxgbe_mac.o \
	mxgbe_phy.o \
	mxgbe_i2c.o \
	mxgbe_gpio.o \
	mxgbe_txq.o \
	mxgbe_rxq.o \
	mxgbe_msix.o \
	mxgbe_ethtool.o \
	mxgbe_net.o \
	mxgbe_pci.o \
	mxgbe_main.o \
	mxgbe_debugfs.o

obj-$(CONFIG_MXGBE) := mxgbe.o
