 # SPDX-License-Identifier: GPL-2.0
 # Copyright (c) 2023 MCST
 
GCOV_PROFILE := n

obj-$(CONFIG_SERIAL_AM85C30_BOOT_CONSOLE) += am85c30.o
obj-$(CONFIG_BOOT_PRINTK) += console.o
obj-$(CONFIG_EARLY_VIRTIO_CONSOLE) += boot_hvc_l.o
