/*
 * SPDX-License-Identifier: GPL-2.0
 * Copyright (c) 2023 MCST
 */

#pragma once

#define RTCFS_CPUID_VENDOR_INTEL	"GenuineIntel"

#define RTCFS_P4_MODEL_NAME		"Intel(R) Pentium(R) 4 CPU 1500MHz"
#define RTCFS_P4_CPUID_STEPPING_ID	0xa
#define RTCFS_P4_CPUID_MODEL		0x0
#define RTCFS_P4_CPUID_FAMILY		0xf
#define RTCFS_P4_CPUID_TYPE		0
#define RTCFS_P4_CPUID_EXT_MODEL	0
#define RTCFS_P4_CPUID_EXT_FAMILY	0
#define RTCFS_P4_CPUID_PHYS_BITS	36
#define RTCFS_P4_CPUID_VIRT_BITS	32
#define RTCFS_P4_CPUID_LEVEL		2

#define RTCFS_CORE2_MODEL_NAME		"Intel(R) Core(TM)2 Duo CPU E7400 @ 1500MHz"
#define RTCFS_CORE2_CPUID_STEPPING_ID	0xa
#define RTCFS_CORE2_CPUID_MODEL		0x7
#define RTCFS_CORE2_CPUID_FAMILY	0x6
#define RTCFS_CORE2_CPUID_TYPE		0
#define RTCFS_CORE2_CPUID_EXT_MODEL	1
#define RTCFS_CORE2_CPUID_EXT_FAMILY	0
#define RTCFS_CORE2_CPUID_PHYS_BITS	39
#define RTCFS_CORE2_CPUID_VIRT_BITS	48
#define RTCFS_CORE2_CPUID_LEVEL		0xa

/* supported cpu features list */
enum {
	RTCFS_X86_FEATURE_FPU = 0,
	RTCFS_X86_FEATURE_VME,
	RTCFS_X86_FEATURE_DE,
	RTCFS_X86_FEATURE_PSE,
	RTCFS_X86_FEATURE_TSC,
	RTCFS_X86_FEATURE_MSR,
	RTCFS_X86_FEATURE_PAE,
	RTCFS_X86_FEATURE_MCE,
	RTCFS_X86_FEATURE_CX8,
	RTCFS_X86_FEATURE_APIC,
	RTCFS_X86_FEATURE_SEP,
	RTCFS_X86_FEATURE_MTRR,
	RTCFS_X86_FEATURE_PGE,
	RTCFS_X86_FEATURE_MCA,
	RTCFS_X86_FEATURE_CMOV,
	RTCFS_X86_FEATURE_PAT,
	RTCFS_X86_FEATURE_CLFSH,
	RTCFS_X86_FEATURE_MMX,
	RTCFS_X86_FEATURE_FXSR,
	RTCFS_X86_FEATURE_SSE,
	RTCFS_X86_FEATURE_SSE2,
	RTCFS_X86_FEATURE_SS,
	RTCFS_X86_FEATURE_SSE3,
	RTCFS_X86_FEATURE_SSSE3,
	RTCFS_X86_FEATURE_CMPXCHG16B,
	RTCFS_X86_FEATURE_PCID,
	RTCFS_X86_FEATURE_SSE4_1,
	RTCFS_X86_FEATURE_SSE4_2,
	RTCFS_X86_FEATURE_POPCNT,
	RTCFS_X86_FEATURES_NUM,
};

/* arch/x86/include/asm/cpufeatures.h */
#define RTCFS_X86_FEATURES_ARRAY				\
{								\
	[RTCFS_X86_FEATURE_FPU]			= "fpu",	\
	[RTCFS_X86_FEATURE_VME]			= "vme",	\
	[RTCFS_X86_FEATURE_DE]			= "de",		\
	[RTCFS_X86_FEATURE_PSE]			= "pse",	\
	[RTCFS_X86_FEATURE_TSC]			= "tcs",	\
	[RTCFS_X86_FEATURE_MSR]			= "msr",	\
	[RTCFS_X86_FEATURE_PAE]			= "pae",	\
	[RTCFS_X86_FEATURE_MCE]			= "mce",	\
	[RTCFS_X86_FEATURE_CX8]			= "cx8",	\
	[RTCFS_X86_FEATURE_APIC]		= "apic",	\
	[RTCFS_X86_FEATURE_SEP]			= "sep",	\
	[RTCFS_X86_FEATURE_MTRR]		= "mttr",	\
	[RTCFS_X86_FEATURE_PGE]			= "pge",	\
	[RTCFS_X86_FEATURE_MCA]			= "mca",	\
	[RTCFS_X86_FEATURE_CMOV]		= "cmov",	\
	[RTCFS_X86_FEATURE_PAT]			= "pat",	\
	[RTCFS_X86_FEATURE_CLFSH]		= "clflush",	\
	[RTCFS_X86_FEATURE_MMX]			= "mmx",	\
	[RTCFS_X86_FEATURE_FXSR]		= "fxsr",	\
	[RTCFS_X86_FEATURE_SSE]			= "sse",	\
	[RTCFS_X86_FEATURE_SSE2]		= "sse2",	\
	[RTCFS_X86_FEATURE_SS]			= "ss",		\
	[RTCFS_X86_FEATURE_SSE3]		= "pni",	\
	[RTCFS_X86_FEATURE_SSSE3]		= "ssse3",	\
	[RTCFS_X86_FEATURE_CMPXCHG16B]		= "cx16",	\
	[RTCFS_X86_FEATURE_PCID]		= "pcid",	\
	[RTCFS_X86_FEATURE_SSE4_1]		= "sse4_1",	\
	[RTCFS_X86_FEATURE_SSE4_2]		= "sse4_2",	\
	[RTCFS_X86_FEATURE_POPCNT]		= "popcnt",	\
}
