# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2023 MCST

rtc_proc-objs := root.o rtcproc.o files.o binfmt.o binfmt_rtc_elf.o binfmt_rtc_elf_compat.o wrappers.o
obj-$(CONFIG_RTC_PROC_FS) += rtc_proc.o
