# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2023 MCST

#
# Arch-specific network modules
#

obj-$(CONFIG_BPF_JIT) += bpf_jit_comp_common.o
obj-$(CONFIG_BPF_JIT) += bpf_jit_asm_common.o

obj-$(CONFIG_BPF_JIT) += cbpf_jit_comp.o
obj-$(CONFIG_BPF_JIT) += cbpf_jit_asm_templates.o

obj-$(CONFIG_BPF_JIT) += ebpf_jit_comp.o
obj-$(CONFIG_BPF_JIT) += ebpf_jit_asm_templates.o
