# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_E2K_DCA) += e2k-dca-provider/
obj-$(CONFIG_DCA) += dca.o
dca-objs := dca-core.o dca-sysfs.o
dca-objs-$(CONFIG_E2K_DCA) += e2k-dca-provider/e2k-dca-provider.o
