#
# Ported in Linux by Alexey V. Sitnikov, alexmipt@mcst.ru, MCST, 2004
#

# for sbus and pci-to-sbus module

obj-$(CONFIG_MBKP1)	+= mbkp1.o
obj-$(CONFIG_MBKP2)	+= mbkp2.o

EXTRA_CFLAGS += -D_KERNEL



